Tc01
cvan8397/SeleniumLevel1 pull request #1
Opened 2021-05-04 05:36 UTC by cvan8397

2021-05-04 18:44 UTC, LoliSlayerMC requested changes

2021-05-04 18:44 UTC, LoliSlayerMC commented on src/main/java/models/Account.java
> +    private String confirmPassword;
confirmPassword is not a valid property

2021-05-04 18:44 UTC, LoliSlayerMC commented on src/test/java/tests/TestBase.java
> +        BrowserHelper.startBrowser(BrowserHelper.DriverType.CHROME);
find another way to pass driver, shouldn't hardcode chrome

2021-05-05 02:34 UTC, cvan8397 commented
@LoliSlayerMC I have fixed my code based on your request. Please review and let me know if any problems

2021-05-05 04:04 UTC, LoliSlayerMC approved these changes
LGTM

2021-05-05 04:32 UTC, merged